---

- hosts: all
  become: yes
  become_method: sudo
  pre_tasks:

  - name: install updates (Fedora)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

  - name: install base packages
    apt:
      name:
        - lnav
        - htop
        - git
        - mc
        - wget
        - curl
        - chkservice
      state: latest
    when: ansible_distribution == "Ubuntu"
